model:
  seed: 1234
  batch_size: 16
  num_workers: 8

  gpus: 2
  default_root_dir: /tmp/gcsfuse_CTRATE/3DMedDiffusion_CT_RATE_training
  resume_from_checkpoint: /project/flame/daesungk/3DMedDiffusion_CT_RATE_training/CT_RATE_model/version_36/checkpoints/epoch=5-step=4000-train/recon_loss=0.20.ckpt
  max_steps: 1000000
  max_epochs: 10000
  precision: bf16

  perceptual_3d: False  
  embedding_dim: 6
  n_codes: 4096
  n_hiddens: 24
  lr: 3e-4
  downsample: [4, 4, 4]
  disc_channels: 24
  disc_layers: 3
  discriminator_iter_start: 3500
  disc_loss_type: hinge
  volume_gan_weight: 2
  l1_weight: 4.0
  gan_feat_weight: 4
  perceptual_weight: 2
  i3d_feat: False
  restart_thres: 1.0
  no_random_restart: False
  norm_type: group
  num_groups: 12
  stage: 1


dataset:
  root_dir: /home/daesungk/3DMedDiffusion/config/CT_RATE_data.json
  image_channels: 1
  imgtype: CT
  patch_size: 64
