model:
  gpus: 4                 # Changed to 4 GPUs
  default_root_dir: /project/flame/daesungk/3DMedDiffusion_CT_RATE_training
  resume_from_checkpoint: 
  max_steps: 1000000
  max_epochs: 10000
  precision: bf16

  perceptual_3d: False  
  embedding_dim: 8
  n_codes: 8192
  n_hiddens: 48
  lr: 3e-4
  downsample: [4, 4, 4]
  disc_channels: 32
  disc_layers: 3
  discriminator_iter_start: 12000
  disc_loss_type: hinge
  volume_gan_weight: 2
  l1_weight: 4.0
  gan_feat_weight: 4
  perceptual_weight: 2
  i3d_feat: False
  restart_thres: 1.0
  no_random_restart: False
  norm_type: group
  num_groups: 24
  stage: 1

dataset:
  root_dir: /home/daesungk/3DMedDiffusion/config/CT_RATE_data.json
  image_channels: 1
  imgtype: CT
  patch_size: 64
